### ISSUE TITLE
Violation of the /tg/ agpl license

### ISSUE THREAD

**Issue by optimumtact** [SwiGs1/LiquidStation-13#32]
Hi there.

Currently you are running a fork of the tgstation code, with the server available to people other than yourself, and by your own admission you are not making the source of this codebase available publicly. 

This is a violation of the terms of the AGPL license of /tg/station which requires that any modifications made be made available in source form to any interested party.

Please make the source available as soon as possible, or you may be subject to legal action under the DMCA by any copyright holder of /tg/station

**Comment by SwiGs1** [comment]
Hello lobotomite 

As stated in the read.me "The New LiquidStation13 Github repository" this is not the new one. This repo is public and available to all therefore not violating the agreement of the license, the source of the new repo was not and will not be stated, and cannot under any doubt reasonable or not be assumed to be said source without proof. But can be assured that for now it is not the source /TransGender/. Both repos are actually available to multiple people that are contributors of LS13 (although most have been removed from here because its archived), your gonna have to do some specifications...

The modifications made are at the interest and purview of LiquidStation13, its proprietors, and other associates, as at this moment in time /tg/ is not being run as the codebase.

After multiple conversations with github support due to people (i think i know who) making multiple github accounts to abuse the issues and pr systems as well as other github systems. As well as raid LS13's other outlets, i was advised and forced into the following events transpired.

Which is fine and legal to ensure the safety of LS13 and everything and everyone related to it. 

 Now you've had to come all the way here to tell the owner of this archived  repo out of 2.5k forks of tgstation, in which you had to tactically and maliciously seek to attempt the use threat of DCMA copyright violations to "strongarm" or "frighten" into getting what exactly?. Its the most pathetic thing I've seen to date. This is an act of targeted fear mongering, and it will not be tolerated. 
As told to the other parties whom have attempted to make similar or the same type of action(s) or threats in any way, shape or form. This will be your only and final warning. 

Leave Liquid Station alone, leave Myself, Sips, Slurps and the other members of Ls13 or liquid gang alone. Or face some harrassment and defamation of character lawsuits, because if need be, it'll be a priority to find those whom wish to continue this course of action and end this situation and continued attacks on LS13 as well as myself, sips and others. Because it was funny the first time, now its beyond a joke.

You do not want to make a situation of this, nor an enemy. Take my word for it. 

To Oranges, and all those associated with the weasel. Do not  attempt to contact Myself, Sips, or any other LiquidStation13 and Liquid Gang, or associated of the latter two. In any way, shape or form, every again. Unless through proper legal channel if you wish to continue acting like monkies with severe brain degradation. Or action will be taken, if need be.

Kind Regards, and a warm fuzzy fuck yourself, LiquidStation13

P.S - enjoy a gitban. (Plus we sincerely doubt you can afford any legal council, anyway. So we enjoy never speaking to you again.)
